amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"   # frame robot
    global_frame_id: "map"            # frame bản đồ
    odom_frame_id: "odom"             # frame odometry
    scan_topic: "/scan"               # topic lidar

    min_particles: 500
    max_particles: 2000

    laser_max_range: 40.0
    laser_min_range: 0.05

    robot_model_type: "nav2_amcl::OmniMotionModel" # robot_model_type: "nav2_amcl::DifferentialMotionModel" # <--- KHAI BÁO SAI HỆ TRUYỀN ĐỘNG!

    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1
    alpha5: 0.1

    transform_tolerance: 1.0


# ==========================================================
# CONTROLLER
# ==========================================================

controller_server:
  ros__parameters:

    use_sim_time: True

    controller_frequency: 20.0

    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    failure_tolerance: 0.3

    controller_plugins: ["FollowPath"]

    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]

    # -------------------------
    # GOAL CHECKER
    # -------------------------

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05     # sai số vị trí goal
      yaw_goal_tolerance: 0.05    # sai số góc
      stateful: True

    # -------------------------
    # PROGRESS CHECKER
    # -------------------------

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3   # robot phải tiến ít nhất 0.3m
      movement_time_allowance: 10.0   # trong 10s

  

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56 # số bước dự đóan trong tương lai
      model_dt: 0.05 # thời gian mỗi bước, xe sẽ nhìn trước 56x0.05 = 2.8s, cần tăng khi xe chạy nhanh hơn
      batch_size: 2000
      
      # Giới hạn vận tốc 
      vx_std: 1.0
      vy_std: 1.0
      wz_std: 0.8
      vx_max: 1.0
      vx_min: -0.4
      vy_max: 1.0
      vy_min: -0.4
      wz_max: 1.0 # omega z hay tốc độ xoay theo z, rad/s
      wz_min: -1.0
      
      iteration_count: 2 # số vòng lặp tối ưu hóa
      prune_distance: 1.7 # khoảng cách để bỏ bớt tài nguyên sau lưng xe để giảm tải cho CPU
      transform_tolerance: 0.1 # thời gian chờ TF, khi nào bị lỗi lệch time TF thì chỉnh sau
      temperature: 0.3 # mức độ bám quỹ đạo, kiểu 0.1 thì bám gắt mà xấu, còn cao hơn như 0.8 thì bám mượt mà dẽ đi lệch quỹ đạo
      gamma: 0.005 # này chưa rõ lắm, hệ số phạt khi xe đánh lái quá gắt, giúp xe chạy êm và mượt hơn
      
      motion_model: "Omni" # bắt buộc phải là Omni thì mới đi ngang được
      visualize: false # để hiện quỹ đạo bên rviz, mà setup sẵn rồi nên tắt đi nhẹ máy
      
      critics:
        ConstraintCritic:
          enabled: true #ép xe ko được vượt quá giới hạn phần cứng bên controller như vận tốc, gia tốc
          cost_power: 1 # hàm bậc 1 tuyến tính
          cost_weight: 4.0
        GoalCritic: 
          enabled: true # lực hút kéo xe về trạm
          cost_power: 1 # cũng là hàm bậc 1 
          cost_weight: 8.0
          threshold_to_consider: 0.3 # ngưỡng so sánh khi cách goal 1.4m thì bắt đầu hút về trạm sạc
        GoalAngleCritic:
          enabled: false # ép xe đỗ đúng góc tại điểm kết thúc, ví dụ ép 90 độ để xe song song với trạm còn cánh tay hướng vô trạm
          cost_power: 1
          cost_weight: 3.0
          threshold_to_consider: 0.5 # ngưỡng khi xe cách goal 0.5 thì bắt đầu canh góc đỗ xe
        ObstaclesCritic:
          enabled: true # né tường và vật cản
          cost_power: 1
          repulsion_weight: 1.5 #taọ lực nhẹ để đẩy xe vừa ra khỏi tường
          critical_weight: 15.0 #lực đẩy mạnh khi sắp đụng tường
          consider_footprint: true # dựa trên hình dáng gầm xe để tính toán va chạm, đã đặt là 1.8 và 0.85
          collision_cost: 100000.0 #Điểm phạt cực nặng nếu đâm tường, MPPI sẽ né bằng mọi giá.
          collision_margin_distance: 0.05 # tạo vùng biên giới va chạm, cách tường 10cm xem như là chạm 
          near_goal_distance: 0.5 # khoảng cách an toàn gần goal, giảm bớt né tường để cắm sạc
        PathAlignCritic:
          enabled: true #ép xe di chuyển trùng với quỹ đạo đường màu xanh lá cay
          cost_power: 1
          cost_weight: 18.0
          max_heuristic_delay: 0.1 # độ trễ cho phép khi tính toán, 0.1s là đủ 
          path_point_step: 2 # bỏ qua 2 điểm gần nhất để ko bị nhiễu, hay hiểu là mỗi bước quỹ đạo là 2 điểm 
        PathFollowCritic: # ép xe ko được lệch khỏi quỹ đạo quá xa
          enabled: true
          cost_power: 1
          cost_weight: 20.0
          offset_from_furthest: 20 # bỏ qua 20 điểm quét được ở xa, để xe tập trung giữ quỹ đạo di chuyển trước mặt, tránh bị rối khi gặp ngã rẽ
          threshold_to_consider: 1.4 # ngưỡng 1.4m để bật/tắt bám quỹ đạo, khi tắt thì sẽ có thg khác làm nhiệm vụ hút vào goal
        PathAngleCritic: # ĐÂY LÀ HÀM ĐỌC CODE C++ BÊN FILE .cpp
          enabled: false
          cost_power: 1
          cost_weight: 15.0
          offset_from_furthest: 4
          threshold_to_consider: 0.5
# Robot rung lắc thì giảm temperature, vx_std
# không bám Path thì tăng PathAlignCritic, va vật cản thì tăng ObstaclesCritic
# ==========================================================
# LOCAL COSTMAP
# ==========================================================

local_costmap:
  local_costmap:
    ros__parameters:

      use_sim_time: True

      global_frame: odom
      robot_base_frame: base_footprint

      update_frequency: 10.0
      publish_frequency: 5.0

      rolling_window: true

      width: 6        # vùng local map 6m
      height: 6
      resolution: 0.05

      footprint: "[[0.9,0.425],[0.9,-0.425],[-0.9,-0.425],[-0.9,0.425]]"

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan

        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
          obstacle_range: 5.0
          raytrace_range: 6.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.7 # Vùng an toàn để né
        cost_scaling_factor: 3.0


# ==========================================================
# GLOBAL COSTMAP
# ==========================================================

global_costmap:
  global_costmap:
    ros__parameters:

      use_sim_time: True

      global_frame: map
      robot_base_frame: base_footprint

      update_frequency: 5.0
      publish_frequency: 2.0

      footprint: "[[0.9,0.425],[0.9,-0.425],[-0.9,-0.425],[-0.9,0.425]]"

      resolution: 0.05

      plugins: ["static_layer","obstacle_layer","inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan

        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.7
        cost_scaling_factor: 3.0


# ==========================================================
# PLANNER
# ==========================================================

planner_server:
  ros__parameters:

    use_sim_time: True

    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true


# ==========================================================
# BEHAVIOR
# ==========================================================

behavior_server:
  ros__parameters:

    use_sim_time: True

    behavior_plugins:
      - spin
      - backup
      - drive_on_heading
      - wait

    spin:
      plugin: "nav2_behaviors/Spin"

    backup:
      plugin: "nav2_behaviors/BackUp"

    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"

    wait:
      plugin: "nav2_behaviors/Wait"


# ==========================================================
# MAP SERVER
# ==========================================================

map_server:
  ros__parameters:

    use_sim_time: True

    yaml_filename: "/home/loc/new_design_ws/src/thietkemoi/thanxe_new_description/maps/my_vinfast_map.yaml"